# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 11:18
from __future__ import unicode_literals

from django.db import migrations


def create_goodies(apps, schema_editor):
    Goods = apps.get_model('goods', 'Goods')
    goodies = ['Chocolate', 'Caramel', 'Cookies', 'Milkshake']

    for goody in goodies:
        Goods.objects.create(name=goody)

class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_goodies)
    ]
